### ISSUE TITLE
Error Trying to Install Version 2.2.1

### ISSUE THREAD

**Issue by mikaelacaron** [TelemetryDeck/SwiftSDK#166] opened 2024-06-30 05:01 UTC
I tried to install TelemetryDeck 2.2.1 onto an older Xcode project that still was deploying iOS 14. There were multiple errors in the Sources > TelemetryClient > Presets > `TelemetryDeck+Purchases.swift` file.

For example line `22` of this file said that there's no property `price` on `transaction`

I bumped the iOS version of the app to iOS 17, but it didn't make a difference. still errors.

I deleted the package, added it again, multiple times but same thing.

I had to change the version to 1.5.1 and use TelemetryClient to make it work

I'm not sure what happened or if this is worth looking into, but just wanted to let you know!

**Comment by Jeehut** [comment] 2024-07-12 11:03
@mikaelacaron Thank you for reporting this. This sounds like a duplicate of https://github.com/TelemetryDeck/SwiftSDK/issues/169 which I fixed in version `2.2.2`. The problem basically was that Apples documentation stated the new fields like `price` or `transaction` are available from Xcode 15 onwards, but in fact it's only available in Xcode 15.1 onwards. So if you tried to build version 2.x in Xcode 15.0 it would fail. But I added another check to exclude the entire `TelemetryDeck+Purchases.swift` file when building with lower than Xcode 15.1.

Please try version `2.2.2` and let me know if you still run into this problem with your exact Xcode version. Closing until you report the fix doesn't work for you.

**Closed by Jeehut** 2024-07-12 11:03 UTC

**Comment by mikaelacaron** [comment] 2024-07-12 22:11
I was using Xcode 15.4, but I agree your change in version `2.2.2` will probably fix it, I'll re-open if I see it again!
